title: Kiki's Drawing Book
author: Rizki Nauli Siregar
email: rizki.siregar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about art, cats, plants, and Indonesia.

theme: minima

# social links
twitter_username: rizkisiregar # DO NOT include the @ character, or else the build will fail!
github_username:  rsiregar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
